/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exercicio3.janela;

import exercicio3.bancobean.ConsultaPessoaBean;
import exercicio3.bancobean.MovimentoBean;
import exercicio3.bancodao.MovimentoDao;
import exercicio3.bancodao.PessoaDao;
import exercicio3.metodos.RandomBanco;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cassio / Leandro
 */
public class Consultar extends javax.swing.JFrame {

    private ArrayList<String> caminhobanco = new ArrayList<String>();
    private List<ConsultaPessoaBean> consultaPessoaBean = new ArrayList<ConsultaPessoaBean>();
    private Integer codigo;
    private int[] ordem;

    /**
     * Creates new form Consultar
     */
    public Consultar() {
        initComponents();
    }

    public void Consultar(ArrayList<String> caminhobanco) {
        this.caminhobanco = caminhobanco;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDados = new javax.swing.JTable();
        jTextNome = new javax.swing.JTextField();
        jButtonConsultar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonCodigo = new javax.swing.JRadioButton();
        jRadioButtonNome = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTableDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cód.Pessoa", "Nome Pessoa", "Logradouro", "Bairro", "Cidade", "Estado", "Pais"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDados);

        jTextNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNomeKeyTyped(evt);
            }
        });

        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar por "));

        jRadioButtonCodigo.setSelected(true);
        jRadioButtonCodigo.setText("Codigo");
        jRadioButtonCodigo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonCodigoItemStateChanged(evt);
            }
        });
        jRadioButtonCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCodigoActionPerformed(evt);
            }
        });

        jRadioButtonNome.setText("Nome");
        jRadioButtonNome.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonNomeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonCodigo)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonNome)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCodigo)
                    .addComponent(jRadioButtonNome))
                .addGap(41, 41, 41))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Consultar");

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonConsultar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(240, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonOK)
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonConsultar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(jButtonOK)
                .addGap(21, 21, 21))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(148, 148, 148)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(71, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCodigoActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        // TODO add your handling code here:
        LimparJtable();
        consultaPessoaBean = null;
        PessoaDao pessoaDao = new PessoaDao();
        if (jRadioButtonCodigo.isSelected()) {
            consultaPessoaBean = pessoaDao.selectPessoa(jTextNome.getText(), 1);
        }
        if (jRadioButtonNome.isSelected()) {
            consultaPessoaBean = pessoaDao.selectPessoa(jTextNome.getText(), 2);
        }

        if (consultaPessoaBean.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nada foi encontrado !!!");
            jTextNome.requestFocus();
            return;
        }

        MostrarDados();
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    public void LimparJtable() {
        ((DefaultTableModel) jTableDados.getModel()).setNumRows(0);
        jTableDados.updateUI();

    }

    private void jTableDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDadosMouseClicked
        // TODO add your handling code here:
        int linha = jTableDados.getSelectedRow();
        ConsultaPessoaBean pessoa = consultaPessoaBean.get(linha);
        codigo = pessoa.getCodiPessoa();
        CadPessoa.jTextCodigo.setText(String.valueOf(codigo));//pessoa
        CadPessoa.jTextNome.setText(pessoa.getNomePessoa());
        CadPessoa.codLogradouro = pessoa.getCodiLogradouro(); //Logrado
        CadPessoa.jTextLogradouro.setText(pessoa.getNomeLogradouro());
        CadPessoa.codBairro = pessoa.getCodiBairro(); //Bairro
        CadPessoa.jTextBairro.setText(pessoa.getNomeBairro());
        CadPessoa.codCidade = pessoa.getCodiCidade(); //Cidade
        CadPessoa.jTextCidade.setText(pessoa.getNomeCidade());
        CadPessoa.codEstado = pessoa.getCodiEstado(); //Estado
        CadPessoa.jTextEstado.setText(pessoa.getNomeEstado());
        CadPessoa.codPais = pessoa.getCodiPais(); //Pais
        CadPessoa.jTextPais.setText(pessoa.getNomePais());
    }//GEN-LAST:event_jTableDadosMouseClicked

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // TODO add your handling code here:
        if (codigo > 0) {
            MovimentoDao movimentoDao = new MovimentoDao();
            MovimentoBean movimento = new MovimentoBean();
            movimento.setDataMovimento(converteData(new java.text.SimpleDateFormat("dd/MM/yyyy").format(new java.util.Date())));
            movimento.setIdPessoa(codigo);
            movimento.setOperacaoMovimento(3);
            movimento.setSiteMovimento(0);
            movimentoDao.insert(movimento, "localhost");
            ordem = new RandomBanco().RandomBancoOrdem();

            for (int i = 0; i < ordem.length; i++) {
                String site = caminhobanco.get(ordem[i]).replace(".", "");
                movimento.setSiteMovimento(Integer.valueOf(site));
                movimentoDao.insert(movimento, "localhost");
            }

            for (int i = 0; i < ordem.length; i++) {
                for (int j = 0; j <= ordem.length; j++) {
                    if (j == 0) {
                        movimento.setSiteMovimento(j);
                        movimentoDao.insert(movimento, caminhobanco.get(ordem[i]));
                    } else {
                        String site = caminhobanco.get(ordem[j - 1]).replace(".", "");
                        movimento.setSiteMovimento(Integer.valueOf(site));
                        movimentoDao.insert(movimento, caminhobanco.get(ordem[i]));
                    }
                }
            }
        }
        CadPessoa.consultar = null;
        dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    private Date converteData(String mydata) {
        Date data = null;
        try {
            DateFormat dtOutput = new SimpleDateFormat("dd/MM/yyyy");
            data = dtOutput.parse(mydata);
        } catch (ParseException e) {
            e.printStackTrace();
        }
        return data;
    }

    private void jTextNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNomeKeyTyped
        // TODO add your handling code here:
        if (jRadioButtonCodigo.isSelected()) {
            String caracteres = "0987654321";
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_jTextNomeKeyTyped

    private void jRadioButtonCodigoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonCodigoItemStateChanged
        // TODO add your handling code here:
        if (jRadioButtonCodigo.isSelected()) {
            jRadioButtonNome.setSelected(false);
        }
        jTextNome.setText("");
    }//GEN-LAST:event_jRadioButtonCodigoItemStateChanged

    private void jRadioButtonNomeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonNomeItemStateChanged
        // TODO add your handling code here:
        if (jRadioButtonNome.isSelected()) {
            jRadioButtonCodigo.setSelected(false);
        }
        jTextNome.setText("");
    }//GEN-LAST:event_jRadioButtonNomeItemStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        CadPessoa.consultar = null;
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void MostrarDados() {
        DefaultTableModel model = (DefaultTableModel) jTableDados.getModel();
        for (int i = 0; i < consultaPessoaBean.size(); i++) {
            model.addRow(new Object[]{"", "", ""});
            ConsultaPessoaBean consultaPessoa = consultaPessoaBean.get(i);
            model.setValueAt(consultaPessoa.getCodiPessoa(), i, 0);//Pessoa
            model.setValueAt(consultaPessoa.getNomePessoa(), i, 1);//Pessoa
            model.setValueAt(consultaPessoa.getNomeLogradouro(), i, 2);//Logradouro
            model.setValueAt(consultaPessoa.getNomeBairro(), i, 3);//Bairro
            model.setValueAt(consultaPessoa.getNomeCidade(), i, 4);//Cidade
            model.setValueAt(consultaPessoa.getNomeEstado(), i, 5);//Estado
            model.setValueAt(consultaPessoa.getNomePais(), i, 6);;//Pais            
        }
        ConsultaPessoaBean consultaPessoa = consultaPessoaBean.get(0);
        codigo = consultaPessoa.getCodiPessoa();
        CadPessoa.jTextCodigo.setText(String.valueOf(codigo));//pessoa
        CadPessoa.jTextNome.setText(consultaPessoa.getNomePessoa());
        CadPessoa.codLogradouro = consultaPessoa.getCodiLogradouro(); //Logrado
        CadPessoa.jTextLogradouro.setText(consultaPessoa.getNomeLogradouro());
        CadPessoa.codBairro = consultaPessoa.getCodiBairro(); //Bairro
        CadPessoa.jTextBairro.setText(consultaPessoa.getNomeBairro());
        CadPessoa.codCidade = consultaPessoa.getCodiCidade(); //Cidade
        CadPessoa.jTextCidade.setText(consultaPessoa.getNomeCidade());
        CadPessoa.codEstado = consultaPessoa.getCodiEstado(); //Estado
        CadPessoa.jTextEstado.setText(consultaPessoa.getNomeEstado());
        CadPessoa.codPais = consultaPessoa.getCodiPais(); //Pais
        CadPessoa.jTextPais.setText(consultaPessoa.getNomePais());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonCodigo;
    private javax.swing.JRadioButton jRadioButtonNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDados;
    private javax.swing.JTextField jTextNome;
    // End of variables declaration//GEN-END:variables
}
